<a href="https://colab.research.google.com/github/LearnFromYourMistakes/GoogleCollab/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we are going to cover the most fundamental concepts of tensors using TensorFlow

More Specifically, going to cover
* intro to tensors
* getting info from tensors
* Tensors and numpy
* using @tf.function(speed up regular py functions)
* Using GPU with TF


In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [5]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
#Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [9]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
# Check the dimension of our vector
vector.ndim

1

In [16]:
#Create a matrix (more than 1 dim)
matrix = tf.constant([[10, 7],
                      [7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [18]:
matrix.ndim

2

In [25]:
# Create another matrix
another_matrix = tf.constant([[1., 2.],
                              [3., 2.],
                              [4., 7.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 2.],
       [4., 7.]], dtype=float16)>

In [27]:
#number of dim of another matrix?
another_matrix.ndim

2

In [28]:
#lets create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [29]:
tensor.ndim

3

What we have created to far :

*scalar
*vector
*matrix
*tensor

#Creating tensors with tf.Variable 

In [42]:
#create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [43]:
#change element in changeable
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
#how about we try assign
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
#change unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

***Rarely in practice will I need to decide whether or not to use constant or varable as tf does this for me, but if in doubt, use constant and change later

###Creating Random Tensors 

In [49]:
random_1 = tf.random.Generator.from_seed(42) # set seed
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle order of elements in a tensor